### ISSUE TITLE
Fix the emulator FLASH_BASE usage

### ISSUE THREAD

**Issue by pekkanikander** [Ell-i/Runtime#20]
The STM32F4 system_stm32f4xx.c requires FLASH_BASE to be defined, as it is needed for initialising SCB->VTOR:

https://github.com/Ell-i/Runtime/blob/master/stm32/system/stm32/src/system_stm32f4xx.c#L374

Hence, for STM32F4 we cannot undefined FLASH_BASE, which would be good any use of FLASH_BASE when compiling for the emulator is a probable bug:
https://github.com/Ell-i/Runtime/blob/master/stm32/emulator/inc/stm32fxxx.h#L35

Obviously, there are multiple ways of fixing this.  One would be to define FLASH_BASE as a C++ object that can be assigned to VTOR but nothing else, but it would be very tricky or even impossible.  Another possibility is to modify our version of system_stm32f4xx.c.  

Probably the best way would be to completely rewrite system_stm32f4xx.c, avoiding the issue.

**Comment by supramaterial** [comment]
After revising the STM32F3 and STM32F4 Series Programming Manual (PM0214 Programming Manual) 

http://www.st.com/st-web-ui/static/active/en/resource/technical/document/programming_manual/DM00046982.pdf

On system reset, the vector table is fixed at address 0x00000000. Privileged software can
write to the VTOR to relocate the vector table start address to a different memory location, in
the range 0x00000080 to 0x3FFFFF80.

As our code assumes a fixed vector table, probably there is no need to add code for moving the table. In particular, as we do not use the macro VECT_TAB_SRAM, the initialization will always put the table again on address 0x00000000, what is absolutely redundant. If the table was not in that position, the code will never reach the Reset_Handler and consequently never execute the SystemInit

**Comment by supramaterial** [comment]
Hi, I propose changing the system initialisation to do not relocate the table. As we apparently do not need it in the foreseeable future. This change applies to all the MCU's based on the Cortex-M4 architecture (both, stm32f4 and stm32f334). I can make the changes if required.

**Comment by pekkanikander** [comment]
Sounds good to me.  Please provide a tested pull request, and I'll merge.  --Pekka

**Comment by pekkanikander** [comment]
Fixed by pull request #26
