### ISSUE TITLE
Compiling for emulator/stm32f334nucleo fails

### ISSUE THREAD

**Issue by latsku** [Ell-i/Runtime#23]
Port for stm32f334nucleo needs preg32_t definitions for emulator. These are defined /stm32/system/stm32/inc/stm32f*xx_extra.h file for other variants.

**Comment by pekkanikander** [comment]
Fixed the initial problem with the missing emulator/inc/stm32f3xx.h.

Now we have the same issue as we had with STM32F4, the assembler startup file that needs to be rewritten in C.  By now that should be almost trivial to anyone, as there are both STM32F0 and STM32F4 examples, which can be used as models.  I can do it later, but my hands are at the moment full with other work.

**Comment by pekkanikander** [comment]
Width with pull request #24
